added shipper data, shipper controller, and shipper routes
ScratchyPDX/CSE341-team-project pull request #3
Opened 2023-11-07 18:10 UTC by Shandaaurich

Everything for the shippers endpoint

2023-11-07 18:26 UTC, ScratchyPDX requested changes

2023-11-07 18:26 UTC, ScratchyPDX commented on routes/shippers.js
> +const { shipperValidationRule, shipperIdValidationRule, validate } = require("../middleware/validator.js");
These validation rules don't yet exist, so the deploy will fail. I included them in "products" because the already existed. You may want to comment this line out and remove their use from lines 16, 18 and 20. We can add them back in later when we work on validation and exception handling. To check for issues with this, execute "npm run start" and make sure the service starts without any errors

2023-11-07 22:49 UTC, Shandaaurich commented on routes/shippers.js
> +const { shipperValidationRule, shipperIdValidationRule, validate } = require("../middleware/validator.js");
done

2023-11-08 01:33 UTC, ScratchyPDX commented
Looks good

2023-11-08 01:34 UTC, merged